[package]
name = "ruchess"
version = "0.0.13"
edition = "2024"
authors = ["zjom"]
license = "Unlicense"
description = "rust chess"
documentation = "https://docs.rs/ruchess"
repository = "https://github.com/zjom/ruchess"

[dependencies]
arrayvec = "0.7.6"

[dev-dependencies]
proptest = "1"

[workspace]
members = ["tui"]

[profile.release]
opt-level = 3
debug = false

[profile.bench]
inherits = "release"
debug = true
