[package]
name = "ruchess"
version = "0.0.14"
edition = "2024"
description = "rust chess"
documentation = "https://docs.rs/ruchess"
repository = "https://github.com/zjom/ruchess"
license = "Unlicense"

[workspace]
members = ["ruchess_tui"]

[lib]
name = "ruchess"

[dependencies]
arrayvec = "0.7.6"

[dev-dependencies]
proptest = "1"

[profile.bench]
inherits = "release"
debug = true

[profile.release]
opt-level = 3
debug = false
