pub mod bitboard;
pub mod board;
pub mod color;
pub mod error;
pub mod game;
pub mod m;
pub mod outcome;
pub mod piece;
pub mod role;
pub mod square;

pub use bitboard::Bitboard;
pub use board::Board;
pub use color::{Color, NUM_COLORS};
pub use error::{MoveError, ParseSquareError};
pub use game::Game;
pub use m::Move;
pub use piece::Piece;
pub use role::{NUM_ROLES, Role};
pub use square::Square;
